const formations = [
  {
    id: 1,
    nom: "Développer l’estime et la confiance en soi des personnes accompagnées",
    category: "Traiter de l’estime de soi en travail social",
    public: "Travailleurs sociaux",
    ref: "ES01",
    date: "12 septembre 2026",
    dateValue: "2026-09-12",
    formateur: "Marie Dupont",
    lieu: "Paris",
  },

  {
    id: 2,
    nom: "Estime de soi et argent : Les systèmes en jeu",
    category: "Traiter de l’estime de soi en travail social",
    public: "Travailleurs sociaux",
    ref: "ES03",
    date: "18 septembre 2026",
    dateValue: "2026-09-18",
    formateur: "Jean Martin",
    lieu: "Lyon",
  },

  {
    id: 3,
    nom: "Le stress : ses effets, ses leviers, le prendre en compte dans l’accompagnement",
    category: "Traiter de l’estime de soi en travail social",
    public: "Travailleurs sociaux",
    ref: "ES04",
    date: "24 septembre 2026",
    dateValue: "2026-09-24",
    formateur: "Sophie Bernard",
    lieu: "Marseille",
  },

  {
    id: 4,
    nom: "Aborder l’hygiène et la propreté avec la personne accompagnée",
    category: "Traiter de l’estime de soi en travail social",
    public: "Travailleurs sociaux",
    ref: "ES05",
    date: "2 octobre 2026",
    dateValue: "2026-10-02",
    formateur: "Thomas Leroy",
    lieu: "Toulouse",
  },

  {
    id: 5,
    nom: "Techniques d’explicitation : mobiliser les savoirs expérientiels des personnes",
    category: "Méthodologie d’intervention sociale",
    public: "Intervenants sociaux",
    ref: "MI01",
    date: "9 octobre 2026",
    dateValue: "2026-10-09",
    formateur: "Claire Moreau",
    lieu: "Bordeaux",
  },

  {
    id: 6,
    nom: "La micro-éthique en acte au service du développement du pouvoir d’agir des personnes accompagnées",
    category: "Méthodologie d’intervention sociale",
    public: "Travailleurs sociaux",
    ref: "MI02",
    date: "12 septembre 2026",
    dateValue: "2026-09-12",
    formateur: "Marie Dupont",
    lieu: "Paris",
  },

  {
    id: 7,
    nom: "Posture professionnelle facilitant le pouvoir d’agir : comment valoriser et impliquer les personnes",
    category: "Méthodologie d’intervention sociale",
    public: "Intervenants sociaux",
    ref: "MI03",
    date: "18 septembre 2026",
    dateValue: "2026-09-18",
    formateur: "Jean Martin",
    lieu: "Lyon",
  },

  {
    id: 8,
    nom: "L'accueil de publics en difficultés, notamment la technique dite de « l’écoute active »",
    category: "Méthodologie d’intervention sociale",
    public: "Intervenants sociaux",
    ref: "MI04",
    date: "24 septembre 2026",
    dateValue: "2026-09-24",
    formateur: "Sophie Bernard",
    lieu: "Marseille",
  },

  {
    id: 9,
    nom: "Dossier de surendettement et procédures de recouvrement de créances : maîtriser les dispositifs pour favoriser l'implication des personnes",
    category: "Difficultés budgétaires – surendettement",
    public: "Travailleurs sociaux",
    ref: "DB01",
    date: "2 octobre 2026",
    dateValue: "2026-10-02",
    formateur: "Thomas Leroy",
    lieu: "Toulouse",
  },

  {
    id: 10,
    nom: "Le co-diagnostic budgétaire : s’appuyer sur les savoirs expérientiels des personnes",
    category: "Difficultés budgétaires – surendettement",
    public: "Travailleurs sociaux",
    ref: "DB02",
    date: "9 octobre 2026",
    dateValue: "2026-10-09",
    formateur: "Claire Moreau",
    lieu: "Bordeaux",
  },

  {
    id: 11,
    nom: "Le secteur bancaire aujourd'hui",
    category: "Difficultés budgétaires – surendettement",
    public: "Intervenants sociaux",
    ref: "DB03",
    date: "12 septembre 2026",
    dateValue: "2026-09-12",
    formateur: "Marie Dupont",
    lieu: "Paris",
  },

  {
    id: 12,
    nom: "L’accompagnement budgétaire : favoriser le pouvoir d’agir des personnes",
    category: "Difficultés budgétaires – surendettement",
    public: "Intervenants sociaux",
    ref: "DB04",
    date: "18 septembre 2026",
    dateValue: "2026-09-18",
    formateur: "Jean Martin",
    lieu: "Lyon",
  },

  {
    id: 13,
    nom: "Accompagner les personnes pendant la procédure de surendettement",
    category: "Difficultés budgétaires – surendettement",
    public: "Travailleurs sociaux",
    ref: "DB05",
    date: "24 septembre 2026",
    dateValue: "2026-09-24",
    formateur: "Sophie Bernard",
    lieu: "Marseille",
    modalite: "Présentiel",
    documents: [],
  },

  {
    id: 14,
    nom: "Crédits, dépenses courantes : les leviers techniques de l'accompagnement budgétaire",
    category: "Difficultés budgétaires – surendettement",
    public: "Travailleurs sociaux",
    ref: "DB06",
    date: "2 octobre 2026",
    dateValue: "2026-10-02",
    formateur: "Thomas Leroy",
    lieu: "Toulouse",
    modalite: "Présentiel",
    documents: [],
  },

  {
    id: 15,
    nom: "Le stress : le comprendre pour en parler",
    category: "Mieux-être au travail",
    public: "Personnes en situation d’emploi",
    ref: "BE01",
    date: "9 octobre 2026",
    dateValue: "2026-10-09",
    formateur: "Claire Moreau",
    lieu: "Bordeaux",
    modalite: "Présentiel",
    documents: [],
  },

  {
    id: 16,
    nom: "Bien-être au travail : savoir se connaître et s’écouter",
    category: "Mieux-être au travail",
    public: "Personnes en situation d’emploi",
    ref: "BE02",
    date: "12 septembre 2026",
    dateValue: "2026-09-12",
    formateur: "Marie Dupont",
    lieu: "Paris",
    modalite: "Présentiel",
    documents: [],
  },

  {
    id: 17,
    nom: "PCB : diagnostic et accompagnement budgétaire, rapport à l’argent, maillage territorial, accès aux droits",
    category: "Special PCB",
    public: "Intervenants PCB",
    ref: "PCB1",
    date: "18 septembre 2026",
    dateValue: "2026-09-18",
    formateur: "Jean Martin",
    lieu: "Lyon",
    modalite: "Présentiel",
    documents: [],
  },

  {
    id: 18,
    nom: "PCB : organiser une action collective",
    category: "Special PCB",
    public: "Travailleurs sociaux / Intervenants PCB",
    ref: "PCB2",
    date: "24 septembre 2026",
    dateValue: "2026-09-24",
    formateur: "Sophie Bernard",
    lieu: "Marseille",
    modalite: "Présentiel",
    documents: [],
  },

  {
    id: 19,
    nom: "PCB : Approfondissement",
    category: "Special PCB",
    public: "Intervenants PCB",
    ref: "PCB3",
    date: "2 octobre 2026",
    dateValue: "2026-10-02",
    formateur: "Thomas Leroy",
    lieu: "Toulouse",
    modalite: "Présentiel",
    documents: [],
  },

  {
    id: 20,
    nom: "La cuisine comme outil pédagogique",
    category: "Formations en intra",
    public: "Intervenants sociaux",
    ref: "IN01",
    date: "9 octobre 2026",
    dateValue: "2026-10-09",
    formateur: "Claire Moreau",
    lieu: "Bordeaux",
    modalite: "Présentiel",
    documents: [],
  },

  {
    id: 21,
    nom: "Développer sa pratique réflexive par une analyse de ses activités professionnelles en acte",
    category: "Formations en intra",
    public: "Intervenants sociaux / encadrement",
    ref: "IN02",
    date: "12 septembre 2026",
    dateValue: "2026-09-12",
    formateur: "Marie Dupont",
    lieu: "Paris",
    modalite: "Présentiel",
    documents: [],
  },

  {
    id: 22,
    nom: "Identification des repères pour l'attribution des aides financières",
    category: "Formations en intra",
    public:
      "Membre ou futur membre d’une commission d’attribution d’aide financière",
    ref: "IN03",
    date: "18 septembre 2026",
    dateValue: "2026-09-18",
    formateur: "Jean Martin",
    lieu: "Lyon",
    modalite: "Présentiel",
    documents: [],
  },
];

export default formations;
